version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: monthly
    groups:
      dependencias:
        patterns: ["*"]
    commit-message:
      prefix: "deps"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      acciones:
        patterns: ["*"]
    commit-message:
      prefix: "ci"
